export const actionType = {
    SET_PAGE_TITLE: "SET_PAGE_TITLE",
    SET_PAGE_ONE: "SET_PAGE_ONE",
    SET_PAGE_TWO: "SET_PAGE_TWO",
    SET_PAGE_THREE: "SET_PAGE_TWO",
    SET_SHOW: "SET_SHOW",
    SET_SEARCH: "SET_SEARCH"
}